### ISSUE TITLE
Trigger phase regex is overly restrictive

### ISSUE THREAD

**Issue by axelson** [insurify/github-asana-action#4]
It looks like the regex requires `**` around the trigger phrase. However that requirement is not documented at all and seems like it could be removed.

**Comment by iamalisajid** [comment]
Thanks for logging the issue @axelson will definitely make a quick fix soon.

**Comment by axelson** [comment]
Thank you!

**Comment by iamalisajid** [comment]
Fixed in release `1.0.1`
Details: https://github.com/insurify/github-asana-action/releases/tag/v1.0.1
